# Generated by Django 4.2.7 on 2024-02-16 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("is_subcategory", models.BooleanField(default=False)),
                ("is_price", models.BooleanField(default=False)),
                ("is_free", models.BooleanField(default=False)),
                ("is_exchange", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="children", to="store.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=31)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=31)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subcategories", to="store.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=9000)),
                ("main_photo", models.ImageField(blank=True, null=True, upload_to="images/")),
                (
                    "price_type",
                    models.CharField(
                        blank=True,
                        choices=[("PRICE", "Price"), ("FREE", "Free"), ("EXCHANGE", "Exchange")],
                        default="PRICE",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("price", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "valuta_type",
                    models.CharField(
                        blank=True, choices=[("SUM", "Sum"), ("EURO", "y.e")], default="SUM", max_length=10, null=True
                    ),
                ),
                ("is_trade", models.BooleanField(blank=True, default=False, null=True)),
                ("email", models.EmailField(default="", max_length=254)),
                ("phone_number", models.CharField(max_length=13)),
                ("views", models.PositiveIntegerField(default=0, editable=False)),
                ("auto_active", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="store.district"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="store.category"
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(blank=True, related_name="favorite_posts", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "recently_viewed",
                    models.ManyToManyField(blank=True, related_name="recently_posts", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "saved_searches",
                    models.ManyToManyField(blank=True, related_name="saved_posts", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="store.subcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="districts", to="store.region"
            ),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="images/")),
                ("is_main", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="store.post"
                    ),
                ),
            ],
            options={
                "unique_together": {("image", "post")},
            },
        ),
    ]
