# Generated by Django 4.2.7 on 2024-02-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("option", "0002_postoptionvalue_rename_title_optionvalue_value_and_more"),
        ("store", "0003_alter_category_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="recently_viewed",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/category/"),
        ),
        migrations.AddField(
            model_name="category",
            name="options",
            field=models.ManyToManyField(blank=True, related_name="categories", to="option.option"),
        ),
        migrations.AddField(
            model_name="post",
            name="options",
            field=models.ManyToManyField(blank=True, through="option.PostOption", to="option.option"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="options",
            field=models.ManyToManyField(blank=True, related_name="subcategories", to="option.option"),
        ),
    ]
