# Generated by Django 4.2.7 on 2024-02-17 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0004_remove_post_recently_viewed_category_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="file",
        ),
        migrations.RemoveField(
            model_name="message",
            name="image",
        ),
        migrations.RemoveField(
            model_name="message",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="message",
            name="post",
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.post")),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyyers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="store.chat"),
            preserve_default=False,
        ),
    ]
