# Generated by Django 4.2.7 on 2024-02-19 00:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0005_remove_message_file_remove_message_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="saved_searches",
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(
                default=1,
                upload_to="files/",
                validators=[django.core.validators.FileExtensionValidator(["png", "jpeg", "pdf", "docx", "txt"])],
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SavedSearches",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("search", models.CharField(max_length=255)),
                ("info", models.CharField(blank=True, max_length=255, null=True)),
                ("is_send", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostsRecently",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.post")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
