# Generated by Django 4.2.7 on 2024-02-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("option", "0003_alter_option_regex"),
        ("store", "0006_remove_post_saved_searches_message_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="options",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="option_values",
            field=models.ManyToManyField(blank=True, related_name="subcategories", to="option.optionvalue"),
        ),
    ]
