# Generated by Django 4.2.7 on 2024-02-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="options", to="store.category"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("CHOICE", "Choice"),
                            ("BUTTON", "Button"),
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("MULTIPLE_CHOICE", "Multiple choice"),
                        ],
                        max_length=15,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=31, null=True)),
                ("is_filter", models.BooleanField(default=False)),
                ("category", models.ManyToManyField(blank=True, through="option.CategoryOption", to="store.category")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to="option.option"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="options", to="store.post"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OptionValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="values", to="option.option"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="option",
            name="post",
            field=models.ManyToManyField(blank=True, through="option.PostOption", to="store.post"),
        ),
        migrations.AddField(
            model_name="option",
            name="subcategory",
            field=models.ManyToManyField(blank=True, related_name="options", to="store.subcategory"),
        ),
        migrations.AddField(
            model_name="categoryoption",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="option.option"
            ),
        ),
    ]
