# Generated by Django 4.2.7 on 2024-02-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("option", "0004_remove_postoptionvalue_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postoption",
            name="value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
