# Generated by Django 4.2.7 on 2024-02-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("store", "0005_remove_message_file_remove_message_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PLan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PLanDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=255)),
                (
                    "choice_text",
                    models.CharField(
                        blank=True, choices=[("WEEK", "7 kun"), ("MONTH", "30 kun")], max_length=255, null=True
                    ),
                ),
                ("amount", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanDetailGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("is_multiple", models.BooleanField(default=False)),
                ("text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.CharField(max_length=20)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.category")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plan.plan")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanDetailPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.CharField(max_length=20)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="store.category")),
                ("plan_detail", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plan.plandetail")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="plandetail",
            name="group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="plan.plandetailgroup"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_detail",
            field=models.ManyToManyField(to="plan.plandetail"),
        ),
    ]
